# engine/app/forensics/metadata/models/__init__.py
from .metadata_ir import (
    ExifToolMetadata,
    PDFStructureReport,
    ObjectGraph,
    MetadataContainer,
)
from .forensic_context import (
    # 子模型
    MetadataIdentity,
    SoftwareProvenanceItem,
    TimelineItem,
    XMPHistoryItem,
    DocumentLineage,
    ImageMetadata,
    PDFIntegrity,
    RevisionDetail,
    RevisionHistory,
    PageText,
    SemanticText,
    FontDistributionItem,
    ImageSummaryItem,
    PageStatistics,
    LayoutSummary,
    AnomalousRegion,
    Annotation,
    Form,
    ActiveContent,
    EmbeddedFile,
    RelevantObject,
    Relationship,
    OrphanObject,
    ObjectGraphSummary,
    # 顶层容器
    ForensicContext,
)

__all__ = [
    # 原有
    "ExifToolMetadata",
    "PDFStructureReport",
    "ObjectGraph",
    "MetadataContainer",
    # 新增
    "MetadataIdentity",
    "SoftwareProvenanceItem",
    "TimelineItem",
    "XMPHistoryItem",
    "DocumentLineage",
    "ImageMetadata",
    "PDFIntegrity",
    "RevisionDetail",
    "RevisionHistory",
    "PageText",
    "SemanticText",
    "FontDistributionItem",
    "ImageSummaryItem",
    "PageStatistics",
    "LayoutSummary",
    "AnomalousRegion",
    "Annotation",
    "Form",
    "ActiveContent",
    "EmbeddedFile",
    "RelevantObject",
    "Relationship",
    "OrphanObject",
    "ObjectGraphSummary",
    "ForensicContext",
]